# -*- coding: utf-8 -*-
"""파일만들기.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aIMrUqK6v8aH0Af71Gn56dYI7CwrfhUm
"""

import os
import pandas as pd
import zipfile

# 1. 압축 파일 풀기
zip_file_path = "/content/drive/MyDrive/2조/췌장암/data/Quantification(normal)_new.zip"  # 압축 파일 경로
extract_path = "extracted_data_normal"  # 압축 해제할 경로

with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

# 2. 데이터 프레임 생성
data = []

# 3. 압축 해제된 폴더 순회 및 데이터 추출
for folder_name in os.listdir(extract_path):
    folder_path = os.path.join(extract_path, folder_name)

    # 폴더인지 확인
    if os.path.isdir(folder_path):
        files = [f for f in os.listdir(folder_path) if f.endswith('.tsv')] # tsv 파일 찾기
        if files:
            tsv_file_name = files[0]  # 첫 번째 tsv 파일 사용
            tsv_file_path = os.path.join(folder_path, tsv_file_name)

            # tsv 파일 읽기
            try:
                with open(tsv_file_path, 'r') as f:
                    lines = f.readlines()[9:]  # 첫 번째 줄 (헤더) 제외
                    for line in lines:
                        values = line.strip().split('\t')  # 탭으로 분리
                        if len(values) == 9:  # 필요한 열 개수 확인
                            data.append([folder_name] + values + [0])  # 폴더 이름, 데이터, 암 유무(정상 : 0, 암 : 1) 추가
            except Exception as e:
                print(f"Error reading file {tsv_file_path}: {e}")
        else:
          print(f"No tsv files found in {folder_path}")

# 4. 데이터 프레임 생성
columns = ['ID','gene_id', 'gene_name',  'gene_type',  'unstranded',   'stranded_first', 'stranded_second',  'tpm_unstranded', 'fpkm_unstranded',  'fpkm_uq_unstranded', 'Cancer']
df = pd.DataFrame(data, columns=columns)

# 5. 결과 확인
print(df.head())

# (선택 사항) CSV 파일로 저장
df.to_csv("normal.csv", index=False)

from google.colab import drive
drive.mount('/content/drive')