# -*- coding: utf-8 -*-
"""normal 다운.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WO3DbwIyUL25ZTcaox5jIDKNnFVtEV1m
"""

!wget https://gdc.cancer.gov/files/public/file/gdc-client_v1.6.1_Ubuntu_x64.zip  # 최신 버전 URL 확인
!unzip gdc-client_v1.6.1_Ubuntu_x64.zip
!chmod +x gdc-client  # 경로 수정

# PATH에 임시로 추가 (선택 사항이지만 권장) - 세션 동안만 유효
import os
os.environ['PATH'] += os.pathsep + os.getcwd() # 현재 작업 디렉토리를 PATH에 추가

import os
import subprocess
import pandas as pd  # 파일 미리보기를 위해 pandas 라이브러리 추가

def download_files_from_uploaded_text(gdc, download_dir="./downloaded_files"):
    """
    코랩에 업로드된 텍스트 파일에서 파일 ID를 추출하고, gdc-client를 사용하여 파일을 다운로드합니다.

    Args:
        filename (str): 코랩에 업로드된 텍스트 파일의 이름입니다.
        download_dir (str, optional): 파일을 저장할 디렉토리 경로. 기본값은 "./downloaded_files"입니다.
    """

    # 다운로드 디렉토리 생성
    os.makedirs(download_dir, exist_ok=True)

    # 텍스트 파일 읽기
    try:
        with open(gdc, "r") as f:
            lines = f.readlines()
    except FileNotFoundError:
        print(f"오류: 파일 '{gdc}'을 찾을 수 없습니다.")
        return

    # 파일 ID 목록 생성
    file_ids = []
    for line in lines:
        line = line.strip()
        if not line or line.startswith("id"):  # 빈 줄이거나 'id'로 시작하는 줄은 건너뜁니다.
            continue
        parts = line.split()
        if parts:
            file_id = parts[0]  # 첫 번째 요소가 파일 ID라고 가정합니다.
            file_ids.append(file_id)

    # gdc-client를 사용하여 파일 다운로드
    for file_id in file_ids:
        try:
            subprocess.run(["gdc-client", "download", "-d", download_dir, file_id], check=True)
            print(f"다운로드 완료: {file_id}")
        except subprocess.CalledProcessError as e:
            print(f"다운로드 실패: {file_id}, 오류: {e}")

    print("모든 파일 다운로드 완료.")

    # (선택 사항) 다운로드된 파일 내용 미리보기
    preview_downloaded_files(download_dir)

def preview_downloaded_files(download_dir, max_files=5):
    """
    다운로드된 파일 중 일부를 미리보기로 보여줍니다.

    Args:
        download_dir (str): 파일이 저장된 디렉토리 경로.
        max_files (int, optional): 미리볼 최대 파일 수. 기본값은 5입니다.
    """
    files = [f for f in os.listdir(download_dir) if f.endswith(".tsv")]
    num_files = len(files)
    print(f"\n총 {num_files}개의 파일이 다운로드되었습니다.")

    if num_files > 0:
        print("\n=== 다운로드된 파일 미리보기 ===")
        files_to_preview = files[:min(max_files, num_files)]  # 처음 몇 개 파일만 선택
        for file in files_to_preview:
            file_path = os.path.join(download_dir, file)
            try:
                df = pd.read_csv(file_path, sep='\t')
                print(f"\n파일명: {file}")
                print(df.head())  # 처음 몇 행만 출력
            except Exception as e:
                print(f"파일 '{file}'을 읽는 중 오류 발생: {e}")
    else:
        print("다운로드된 파일이 없습니다.")

# 코랩에 업로드된 텍스트 파일 이름
uploaded_file_name = "cnv(normal_only).txt"  # 실제 파일 이름으로 변경

# 함수 호출
download_files_from_uploaded_text(uploaded_file_name)

import shutil
from google.colab import files
# 폴더 경로
folder_path = '/content/downloaded_files'

# ZIP 파일로 압축 (폴더 -> ZIP 파일)
shutil.make_archive('/content/downloaded_files', 'zip', folder_path)

# 다운로드
files.download('/content/downloaded_files.zip')